### ISSUE TITLE
GPG key.

### ISSUE THREAD

**Issue by Tsutsukakushi** [maqp/tfc#1]
Your GPG key has expired. 

I tried to email you about this but you probably haven't noticed.

**Comment by maqp** [comment]
The only GPG key I'm currently using is TFC signing key

    pub   rsa4096 2016-09-21 [SC] [expires: 2017-09-21]
          26CA684ADB71CFD82C15491165DAD0E65330514E
    uid           [ unknown] Markus Ottela (TFC signing key) <oottela@cs.helsinki.fi>

This is because GPG lacks forward secrecy and deniability I prefer my private communications (with people I know and trust) to have. As TFC is a FOSS project, transparency trumps trust; You should not contact me in matters that can not be discussed in public. Also in this case, your primary means of ensuring physical security and privacy should be anonymity (Tor and maybe public Wifi hotspots).

Also, I have not received your email.

**Comment by Tsutsukakushi** [comment]
Oh fuck. Sorry, this went to the wrong github repo. This is why I prefer email.
