### ISSUE TITLE
Security model does not consider hardware/firmware backdoors?

### ISSUE THREAD

**Issue by DenisNovac** [maqp/tfc#10]
Hi everyone.

If i understand right, diode model will protect me from new incoming malware/attacks. But what if my Source machine is sending data by some firmware backdoor without being controlled from outside (by schedule or something)?

**Comment by maqp** [comment]
If that's the case, you'd just have to use other hardware that doesn't have the infected piece of firmware, a Purism Librem laptop for example. If this turns out to be a wider problem, an FPGA, or compact implementation on a microcontroller.

If none of that is possible, that would implicate that it's impossible to have secure encrypted communication with computers. This is because no matter what hardware you buy, the device will use any channel you'd output ciphertexts through to spit out sensitive keys, all on its own, with no exploit or even remote activation command for some dormant malware (which the data diode currently prevents the Source Computer from receiving). If you can show this to be the case, let us know so we can run into the mountains screaming; at that point there's no hope left for secure communication. It would save the entire infosec community a lot of time wasted on programming security systems.

That being said, we need to assume what you propose is not the case. If it can be shown to be, figuring out where to obtain trustworthy hardware becomes the top priority for the entire infosec community.

**Comment by DenisNovac** [comment]
That's fair, thank you.
