### ISSUE TITLE
Chacha20-Poly1305 is not secure enough. Upgrade to AES256 or Serpent-256/512 ?

### ISSUE THREAD

**Issue by mikebdp2** [maqp/tfc#11]
I.e.

> On Wednesday, March 6, the OpenSSL team revealed a low severity vulnerability in the ChaCha20-Poly1305, an AEAD cipher that incorrectly allows a nonce to be set of up to 16 bytes.

From the information available online, to me it seems the only real advantage of Chacha20 - compared to the more secure alternatives - is a speed. However, for a Tinfoil Chat to justify its' name and purpose, security should be taken as a top priority.

Please consider something like AES256 - or, even better, Serpent-256: https://en.wikipedia.org/wiki/Serpent_(cipher) . Serpent took a 2nd place at AES contest - and, while being stronger than AES/Rijndael, lost to it only because of its' slightly slower speed.

Maybe take a Serpent-512 implementation from https://github.com/Steppenwolfe65/CEX-NET ? Or serpent-xts 512b from cryptsetup, or something like this if you know better...

**Comment by maqp** [comment]
Hi, looks like you're referring to [this](https://www.openssl.org/news/secadv/20190306.txt).

Firstly, TFC doesn't use the OpenSSL implementation for ChaCha, but [Libsodium](https://github.com/jedisct1/libsodium) implementation via the [PyNaCl](https://github.com/pyca/pynacl/) library.

Secondly, TFC doesn't use ChaCha20-Poly1305, but XChaCha20-Poly1305. The [latter](https://libsodium.gitbook.io/doc/secret-key_cryptography/aead#availability-and-interoperability) takes neither 12 byte, nor 16 byte nonces, but a 24-byte nonce. This allows safe use of random nonces.

In TFC nonces are generated [using the csprng() function](https://github.com/maqp/tfc/blob/master/src/common/crypto.py#L538):


    nonce = csprng(XCHACHA20_NONCE_LENGTH)

    try:
        ct_tag = nacl.bindings.crypto_aead_xchacha20poly1305_ietf_encrypt(plaintext, ad, nonce, key)  # type: bytes
    except nacl.exceptions.CryptoError as e:
        raise CriticalError(str(e))

The XCHACHA20_NONCE_LENGTH is fixed to [24 bytes](https://github.com/maqp/tfc/blob/master/src/common/statics.py#L556):

    XCHACHA20_NONCE_LENGTH = 24

The csprng() function loads the entropy from GETRANDOM and validates that the length it returns is correct both [inside the function](https://github.com/maqp/tfc/blob/master/src/common/crypto.py#L1070):

    entropy = os.getrandom(key_length, flags=0)  # type: bytes

    if len(entropy) != key_length:
        raise CriticalError(f"GETRANDOM returned invalid amount of entropy ({len(entropy)} bytes).")

and [inside the BLAKE2b compressor function](https://github.com/maqp/tfc/blob/master/src/common/crypto.py#L135) that follows GETRANDOM:


    if len(digest) != digest_size:
        raise CriticalError(f"BLAKE2b digest had invalid length ({len(digest)} bytes).")

So TFC has checks that will gracefully exit if the nonce size is anything other than the specified 24 bytes.

The PyNaCl library also [validates](https://github.com/pyca/pynacl/blob/master/src/nacl/bindings/crypto_aead.py#L379) the nonce size:

    ensure(isinstance(nonce, bytes) and
           len(nonce) == crypto_aead_xchacha20poly1305_ietf_NPUBBYTES,
           'Nonce must be a {0} bytes long bytes sequence'.format(
               crypto_aead_xchacha20poly1305_ietf_NPUBBYTES),
           raising=exc.TypeError)

the `crypto_aead_xchacha20poly1305_ietf_NPUBBYTES` is set to 24 bytes [here](https://github.com/pyca/pynacl/blob/master/src/libsodium/src/libsodium/include/sodium/crypto_aead_xchacha20poly1305.h#L22):

    #define crypto_aead_xchacha20poly1305_ietf_NPUBBYTES 24U

Lastly, nonces in TFC are mostly useless because they are only needed if the key stays the same across multiple encryption operations. Even if TFC used a fixed nonce, the hash ratchet functionality that enables forward secrecy means each packet is encrypted with a key that is the BLAKE2b hash of the previous key. The nonces offer defense in depth -- e.g. if the user would for some reason mess up and restore an old backup of their key database. This would mean the user would use same symmetric keys for a second time. However, since the nonces would be different, it wouldn't be a problem. As for usability, the recipient wouldn't be able to decrypt the messages since the keys were expired, and they could let the user know they are getting warnings about the user using expired keys.

---

As for AES and Serpent, AES-GCM which is the recommended AEAD scheme is [hard to get right](https://eprint.iacr.org/2013/157.pdf). While I do trust e.g. the [Libsodium implementation](https://libsodium.gitbook.io/doc/secret-key_cryptography/aead/aes-256-gcm), one issue is that unlike XChaCha20, AES is not secure against cache timing attacks on hardware that doesn't support AES-NI. XChaCha20 is also faster, and has no security issues as far as we know. In fact, the Poly1305-tag has a nice security proof since it's a Wegman-Carter MAC, and it's AFAIK much easier to implement the AEAD scheme, which means it's less likely to have errors, and more likely to have any errors found. Serpent was indeed the strongest AES-finalist, but it has no robust implementations (I've looked).

So to conclude, the OpenSSL's issue with nonces doesn't touch TFC in any way. I'm closing this as a non-issue. Feel free to comment and re-open if necessary.
