### ISSUE TITLE
Clarification re: where the public key is being typed into

### ISSUE THREAD

**Issue by elimisteve** [maqp/tfc#17]
> To allow key exchanges, the short elliptic-curve public keys are input manually by the user.

Input manually _into the Source_ computer, yes?

(And too bad it wouldn't be as secure to allow the Source computer to scan a QR code containing the public key, hmm...)

**Comment by maqp** [comment]
>Input manually into the Source computer, yes?

Yes. The numbered list discusses each device in isolation, text under "2" discusses Source Computer (and its data diode).

>(And too bad it wouldn't be as secure to allow the Source computer to scan a QR code containing the public key, hmm...)

I've seen [webcam-QR-code implementations before](https://www.youtube.com/watch?v=D_xrlAGzQfs), but I'm unsure it's safe because you can't really check the size and content of what you're about to import. So it increases attack surface unnecessarily. The way I see it, only situation QR-codes should be implemented is, if the [NIST post-quantum competition](https://csrc.nist.gov/projects/post-quantum-cryptography) selects a winner with very large public keys that would make adding contacts very tedious.

**Comment by maqp** [comment]
The ticket's been open for quite some time, I'm assuming you're satisfied with the answer, so I'll close this. Feel free to comment/re-open if necessary.
