### ISSUE TITLE
Use mixnet instead of Tor

### ISSUE THREAD

**Issue by rabutial** [maqp/tfc#30]
Security could be greatly increased by using a mixnet. User experience could potentially then also be improved by making offline cryptographic operations optional. See: https://github.com/nym-hackathon/ideas/issues/9

**Comment by maqp** [comment]
The discussion in the ticket been quiet for a month now so I'm closing it. Feel free to comment and open if necessary.

**Comment by rabutial** [comment]
Sorry for the delay in responding to this.

> The [latest release of Mixmaster is from 2008](https://en.wikipedia.org/wiki/Mixmaster_anonymous_remailer) and [for Mixminion, latest is from 2007](https://en.wikipedia.org/wiki/Mixminion). Since the threat model wrt metadata is primarily protected by the network facing components, the security of them depends on patching vulnerabilities. Thus using unmaintained software isn't really beneficial wrt overall security, even if mixnets look better on paper in some respects.

That's a good point, but the suggestion was not so much directed at Mixmaster/Mixminion but rather on the "next generation" mixnet projects like Nym (where the suggestion is attached) or Katzenpost.

> It's also unclear to me what kind of latency users would expect. TFC is for ~instant messaging where only a few second latency is acceptable. It is my understanding, the security of mixnets is based on high latency which is better suitable for e.g. emails that are traditionally more thoughtful compositions, with expected response times varying between hours, days, or even weeks.

My understanding is that Nym, at least, is intended to achieve latency in the few-seconds range. However, I see nothing in the design of TFC which demands such low latency or prohibits someone from using TFC like they would use email.

> > User experience could potentially then also be improved by making offline cryptographic operations optional.
> 
> I'm not sure whether or not you're referring to the database encryption with the master password, or the encryption/decryption of messages on Source/Destination Computers, so I'll do both:

I was primarily referring to message encryption/decryption, see below.
 
>     2. The split TCB architecture is what separates TFC from other Tor Onion Service based messaging software, such as Cwtch and Briar.

Yes, that's true. The split TCB architecture is a major selling point of TFC. However it is also a major *disadvantage*. What if I, as a TFC user, want to chat with someone who will not go to the trouble of setting up their endpoints in a secure manner?

The current design forces me to make a choice: either I can only communicate with people who are equally paranoid as I am (and who have the time/expertise to set up TFC) or I can use a less secure system.

Call it the "Glenn Greenwald problem" ... when Edward Snowden wanted to leak his documents, the first journalist he approached (Greenwald) could not be persuaded to learn how to use GPG. (much less TFC!)

But there is still a significant benefit to having at least one of the two endpoints using a split TCB architecture, especially if it is more difficult for an adversary to target the less-secure end of the conversation.

> When it comes to protecting the endpoint from remote exploits, the benefits to anonymization that mixnets provide over Tor are incremental at best, thus improvement to "which endpoint should I hack" is never comparable to "even If I know the endpoint's IP-address, I still couldn't remotely exfiltrate keys due to the HW isolation design."

My understanding is that this is not true, and mixnets provide significant anonymization benefits compared with Tor. End-to-end correlation can be addressed with cover traffic, for example. (I believe both Nym and Katzenpost do this)

> Finally, quick comment from the peanut gallery wrt the link you posted; While QR codes may be an easy way for initial implementation and uptake, the hardening to guarantee there are no QR code parsing exploits (which the post touched on) is really tough a problem.

Yes, that is why one proposed solution (the Specter DIY device) uses a hardware QR code reader with serial/UART one-way communication to the host. There are still benefits to allowing less-paranoid less-savvy users to use simpler/lower effort approaches, however.

>The split TCB architecture is much more simple to audit, and while there's some up-front cost and effort involved in the assembly, having no overhead wrt manual labor during use, ultimately makes for a better UX. I'd argue the novelty factor of endless QR-code scans wears out quite fast.

The split TCB architecture is fantastic for what it is, and this is not intended to replace it outright. Rather, the "half-TCB" approach would make it much more likely and much more feasible for people to *use* this architecture, by allowing TCB/TFC users to communicate with less-savvy/less-paranoid counterparties.

**Comment by maqp** [comment]
>That's a good point, but the suggestion was not so much directed at Mixmaster/Mixminion but rather on the "next generation" mixnet projects like Nym (where the suggestion is attached) or Katzenpost.

Ah I see. Since TFC originally started as a plugin for Pidgin, the codebase isn't designed from the ground up for v3s. Nym could of course provide an API that allows interfacing with other software, but that requires forking TFC and modifying the network identifier accounts. I'd rather not introduce additional complexity for users with textual questions (choosing the endpoint configuration and key exchange is already asking a bit too much), especially given that the SW lacks user friendly GUI, which would require massive work I'm not able to do for quite some time.

A few second delivery time is fine but I wonder what benefit the mixnet then has over Tor wrt end-to-end correlation attacks.

>What if I, as a TFC user, want to chat with someone who will not go to the trouble of setting up their endpoints in a secure manner?

Then you would ask them to either setup the Qubes configuration (best you can do with SW alone) or local testing version and advice them to be upfront to all their contacts wrt. their endpoint configuration and take that into account when messaging them. All three configurations are inter-operable

* Local testing configuration (no endpoint security, runs on pretty much all Ubuntu flavors)
* Qubes configuration (some endpoint security via Xen based isolation via virtualization)
* Hardware configuration (strong endpoint security via HW data diode)

But as the threat model explains, everyone should* use the same configuration. E.g., if you have personally invested in HW isolation, you can naturally only have endpoint security with other contacts and groups that all use the HW isolation. If your peer, or a single contact in the group uses Qubes / local testing configuration, that user is the weakest link, and compromising their endpoint with SW exploit will compromise the entire group chat content, or all 1:1 chats from that side. Unfortunately there's no magical fix to this issue.

\* (I think the article says `must`, but that's a security-consideration not a technical necessity)

I've given some thought to have the client leak the endpoint configuration to peers over the E2EE channel so that a user's incompetence wouldn't compromise security of others in e.g. a group chat. However, this could incentivize some users to modify their clients to lie about their endpoint configuration (it would at most require changing a single constant), and that false trust could be even more dangerous. My current rationale is, it's better for the application to not reveal that, so users who don't know their peers well enough to e.g. visit their houses to see their endpoint HW, are unconsciously more vary about how much trust they put into the comms channel of the group / contact.

>However it is also a major disadvantage. 

If we strip out the endpoint security aspect, we're left with effectively a fork of Briar or Cwtch.im, but with much worse UI. So I'd argue it makes very little sense in using TFC local testing, unless the the threat model is very specific, e.g. one that assumes attacker doesn't exploit the endpoint, but that avoids adversaries with quantum computers decrypting traffic retrospectively in the future (PSKs in TFC are post-quantum).

I didn't set out with TFC to create yet another messenger, I wrote it to address endpoint security in particular. An indicative of this is, the very first lines of code written for TFC, were about sending a packet over the serial link and the data diode. Also, the very first drawing of TFC was about the three computer layout.

>when Edward Snowden wanted to leak his documents, the first journalist he approached (Greenwald) could not be persuaded to learn how to use GPG.

I completely understand. TFC doesn't suit too well for the context of whistleblower-journalist, especially if the journalist doesn't have readily available endpoint. One particular issue here is what we assume the capabilities of attacker are, and what level of authenticated channels are at users' disposal. 

Let's say Greenwald has HW isolated endpoint ready. Now the cheapest attack for the NSA is TLS-MITM of `theintercept.com/contact-us`, from where GG's TFC account could be found. As there's no strongly authenticated channel to obtain the TFC account, MITM attack overrides any security TFC can provide. Now if Poitras serves as a trusted middle-man that improves that chances of obtaining correct TFC account, but again, it's risky (Snowden didn't know even Poitras personally), and endpoint security doesn't make too much sense because you don't need to exploit Snowden/GG endpoint, only The Intercept's / Poitras' contact info page.

So because not even the MITM risk can be solved, it makes very little sense in being concerned about post-quantum security (which shouldn't be done with TFC anyway, the first chance Snowden had to meet GG, was in the Miranda hotel, and using TFC at that point made very little sense). (Staying in touch afterwards, that's another story.)

In comparison, when used by peers who know each other (a group of dissidents/activists) and who can establish strong authenticated channels for TFC account and fingerprint verification, the endpoint security becomes a much more important issue.

>especially if it is more difficult for an adversary to target the less-secure end of the conversation.

That would hold true if one peer managed to get the Relay Program to run e.g. on OpenBSD that's quite hardened by default. But I'd rather not make assumptions such as "which OS exploits does the attacker have available". TFC tries to start from the PoV of "assume the attacker has universal exploit", but I admit this has gotten more and more murky over time with the introduction of local testing, and later, Qubes configuration.

>End-to-end correlation can be addressed with cover traffic, for example.

TFC tries to do this as well. The relay program's client makes queries at more or less constant rate to the server. If the server has no messages, it responds with empty string, and Tor cells are always padded. Thus short messages should look identical, but large messages/file octet streams will naturally be distinct. (Note: I haven't verified the packet sizes, and making this feature robust would require a lot of expert work. So it's potentially a nice-to-have, but nothing is guaranteed and thus it's not advertised.) There's also the TFC's traffic masking mode where Source Computer hides even from the Relay Program when the user is actually sending a file / message. This one is something that's within the endpoint security guarantees so the focus wrt traffic masking went there.

One reason for this is, there's also the case traffic confirmation can also be done with "kill power from house and see if particular v3 onion service goes down".

I don't know enough about mixnets to be sure which attacks work against it especially with the advertised low latency. To quote GCHQ "Tor is still the king of low-latency anonymity solutions with no contenders to the throne". That was of course some time ago but until there's peer review, track record, and recommendations by experts, I'd rather not add further complexity. Once Nym is more mature, and a proven, safer alternative, I'll most likely have no quarrel in switching.

**Comment by rabutial** [comment]
>Ah I see. Since TFC originally started as a plugin for Pidgin, the
>codebase isn't designed from the ground up for v3s. Nym could of course
>provide an API that allows interfacing with other software, but that
>requires forking TFC and modifying the network identifier accounts. I'd
>rather not introduce additional complexity for users with textual
>questions (choosing the endpoint configuration and key exchange is
>already asking a bit too much), especially given that the SW lacks user
>friendly GUI, which would require massive work I'm not able to do for
>quite some time.

That makes sense. However, Nym in particular may be a drop-in
replacement for Tor ... there is a nym-socks5-client which presents the
Socks5 interface which (I think) TFC already uses.

>A few second delivery time is fine but I wonder what benefit the mixnet
>then has over Tor wrt end-to-end correlation attacks.

I don't know enough to give a detailed technical explanation, but my
general understanding is there is significant benefit compared to Tor.

>>What if I, as a TFC user, want to chat with someone who will not go to
>>the trouble of setting up their endpoints in a secure manner?
>
>Then you would ask them to either setup the Qubes configuration (best
>you can do with SW alone) or local testing version and advice them to
>be upfront to all their contacts wrt. their endpoint configuration and
>take that into account when messaging them.

Okay, so that's basically what I'm proposing already... except that I
would suggest using a v3 mixnet to reduce the odds that an adversary
will compromise your counterparty's Qubes install to read what you
write.

>But as the threat model explains, everyone should* use the same
>configuration. E.g., if you have personally invested in HW isolation,
>you can naturally only have endpoint security with other contacts and
>groups that all use the HW isolation.

Yes, exactly. The benefit which I see of using the mixnet is that
both-parties-using-same-setup is no longer as strict a requirement.

If you personally are using HW isolation, you can communicate with much
greater security with a non-HW isolation-using counterparty if you are
communicating over a mixnet, rather than communicating over a network
where the locations of both endpoints are known to the adversary.

>I've given some thought to have the client leak the endpoint
>configuration to peers over the E2EE channel so that a user's
>incompetence wouldn't compromise security of others in e.g. a group
>chat. However, this could incentivize some users to modify their
>clients to lie about their endpoint configuration (it would at most
>require changing a single constant), and that false trust could be even
>more dangerous. My current rationale is, it's better for the
>application to not reveal that, so users who don't know their peers
>well enough to e.g. visit their houses to see their endpoint HW, are
>unconsciously more vary about how much trust they put into the comms
>channel of the group / contact.

This is a little outside the scope of this issue. My opinion: any user
sophisticated enough to modify their client, will be sophisticated
enough to use HW isolation or another "sophisticated" solution.
Therefore, publishing endpoint configuration is at worst an incentive to
learn the technical skill needed to set up HW isolation.

>If we strip out the endpoint security aspect, we're left with
>effectively a fork of Briar or Cwtch.im, but with much worse UI.

Just to be clear, I am not at all recommending stripping the endpoint
security. Rather, I'm suggesting making it possible to make the endpoint
security measures of TFC usable in an exponentially larger set of
circumstances. (i.e where a sophisticated, HW-isolation-using person is
communicating with someone less sophisticated who is simultaneously less
under threat)

>Let's say Greenwald has HW isolated endpoint ready. Now the cheapest
>attack for the NSA is TLS-MITM of `theintercept.com/contact-us`, from
>where GG's TFC account could be found. As there's no strongly
>authenticated channel to obtain the TFC account, MITM attack overrides
>any security TFC can provide.

That's not true. Any adversary who is executing a MITM attack against
+everyone* who accesses GG's published TFC account data will quickly be
discovered. Many of the people with whom GG communicates will e.g meet
GG in person, or know GG's account from other channels.

Bulk MITM is therefore extremely risky. The adversary would have to
specifically MITM the contact data of every journalist Mr. Snowden looks
up, but only when it's Snowden specifically who is looking at the page.
This is much more difficult (journalists make contact data available
in a highly dispersed and heterogenous form) and less useful. (they, at
this point, have to already know enough to suspect him in particular)

Attacking the contact info of *every* journalist visible to *everyone*
would be exponentially riskier, for the reasons given above.

>In comparison, when used by peers who know each other (a group of
>dissidents/activists) and who can establish strong authenticated
>channels for TFC account and fingerprint verification, the endpoint
>security becomes a much more important issue.

Yes, but in this scenario there are also very likely people in the group
who are less sophisticated and/or less tolerant of bulky endpoint
security measures, such as TFC's hardware endpoint isolation.

In this case it is still better if *some* people in the group use HW
isolation, and a mixnet to communicate with those people in the group
who don't understand or can't be bothered with HW isolation.

>>especially if it is more difficult for an adversary to target the
>>less-secure end of the conversation.
>
>That would hold true if one peer managed to get the Relay Program to
>run e.g. on OpenBSD that's quite hardened by default. But I'd rather
>not make assumptions such as "which OS exploits does the attacker have
>available". TFC tries to start from the PoV of "assume the attacker has
>universal exploit", but I admit this has gotten more and more murky
>over time with the introduction of local testing, and later, Qubes
>configuration.

Yes, and this idea of "assume the attacker has a universal exploit" is
why the mixnet is so useful. We assume the attacker can exploit any
system they are able to identify. Then we make it difficult for the
attacker to identify the system, using the mixnet.

The systems which we assume the attacker *can* identify and exploit
using their universal exploit, we protect with HW isolation.

>
>>End-to-end correlation can be addressed with cover traffic, for example.
>
>TFC tries to do this as well. The relay program's client makes queries
>at more or less constant rate to the server. If the server has no
>messages, it responds with empty string, and Tor cells are always
>padded. Thus short messages should look identical, but large
>messages/file octet streams will naturally be distinct. (Note: I
>haven't verified the packet sizes, and making this feature robust would
>require a lot of expert work. So it's potentially a nice-to-have, but
>nothing is guaranteed and thus it's not advertised.) There's also the
>TFC's traffic masking mode where Source Computer hides even from the
>Relay Program when the user is actually sending a file / message. This
>one is something that's within the endpoint security guarantees so the
>focus wrt traffic masking went there.

That's definitely a good start!

>One reason for this is, there's also the case traffic confirmation can
>also be done with "kill power from house and see if particular v3 onion
>service goes down".

I believe the Katzenpost mixnet (a Nym alternative) has some measures to
deal with this, but I don't recall the details.
