### ISSUE TITLE
Devices

### ISSUE THREAD

**Issue by PowerPress** [maqp/tfc#8]
So the network computer is supposed to be running TAILS OS correct? What about the destination/source systems? Are they supposed to be raspberry Pi's or laptop or something else?

**Comment by maqp** [comment]
>So the network computer is supposed to be running TAILS OS correct?

Unfortunately at the moment the Networked Computer setup requires *ubuntu 19.04. Tails 3.13.2 (the current version) only comes with python 3.5.3 that doesn't support f-strings among other things.

Currently if you try to install `relay` configuration on Tails 3.13.2, git fails to clone the repository through Tor (`Could not resolve host: github.com`)  so that remains to be resolved too.

Once Tails 4.0 is released, it'll hopefully come with OnionShare 2.1 and that way, with many up-to-date PIP-dependencies from `Flask` to `Stem` that TFC shares with OnionShare. This will make installation faster.

>What about the destination/source systems?

Not sure if the question was about the former topic (Tails) or latter (RPi) so I'll do both.

For Source/Destination Computers, Tails doesn't have major benefits as there has to be persistence anyway for the databases. The benefit of using Tails for Networked Computer is every endpoint looks pretty much the same (there's no personal files that could be used to identify who the endpoint belongs to), and that it forces all connections through Tor, which isn't the case with *buntu.

> Are they supposed to be raspberry Pi's or laptop or something else?

Source/Destination are ideally cheap netbooks with removable wireless network card that allows air gapping the system reliably. Raspberry Pi support has been dropped as the BCM2837 CPU sandwitches the BCM43438 WLAN chip into the CPU itself. Airgapping RPi3 (that stores currently sell) on hardware level is practically impossible.

Raspberry Pi isn't the ideal form factor, and once you add a fast SD-card, a decent display, peripherals, a battery and a charging solution for it, the price difference between cheap netbooks isn't worth the hassle IMO, even if you used earlier generation RPis that could be air gapped.

**Comment by PowerPress** [comment]
Awesome response. I remember in prior versions the RPI was the ideal candidate but your suggestions make perfect sense especially with the integrated WiFi and etc.

**Comment by maqp** [comment]
Hopefully in the future I'll be able to expand support for some SoCs that don't have built-in Wi-Fi. I'm closing this for now, feel free to comment / re-open if needed.
